### ISSUE TITLE
Unhandled Exception if Roblox Path is Empty

### ISSUE THREAD

**Issue by RGBProductions** [MichaelEpicA/RBXTools#3]
If you do not provide any path, RBXTools throws an error:
```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at RBXTools.Roblox.InputRobloxFolder()
   at RBXTools.Roblox.FindRobloxFolder(Boolean force)
   at RBXTools.Program.Main(String[] args)
```
It should instead tell the user that they provided an empty path and ask them to try again.

**Comment by Frisk9571** [comment]
i'm fairly sure if you don't input a path it's not on accident.

**Comment by MichaelEpicA** [comment]
Fixed in commit: https://github.com/MichaelEpicA/RBXTools/commit/ad06ac4b94c2025b8c7145812b50060240b23cff
