### ISSUE TITLE
OutOfRange Exception.

### ISSUE THREAD

**Issue by Frisk9571** [MichaelEpicA/RBXTools#4]
![image](https://user-images.githubusercontent.com/81794832/181872009-fdf30ae1-0203-46ec-8065-4a5984450305.png)

**Comment by MichaelEpicA** [comment]
Fixed in commit: https://github.com/MichaelEpicA/RBXTools/commit/3fc2574a897f7ae9d7d031ea7ce2e4bcc65d0d9a
