### ISSUE TITLE
Autoupdate error while disconnected to internet.

### ISSUE THREAD

**Issue by Frisk9571** [MichaelEpicA/RBXTools#5]
![image](https://user-images.githubusercontent.com/81794832/181872164-3d7ddd76-ed06-4206-99b5-d5d34f576e33.png)

**Comment by MichaelEpicA** [comment]
Thank you! If someone was trying to use this tool offline, this would of been bad.

**Comment by MichaelEpicA** [comment]
Fixed in commit: https://github.com/MichaelEpicA/RBXTools/commit/a1a01a079de4d27c9035b70e3093e91051750481
