### ISSUE TITLE
Add a question if you want to back up your roblox folder

### ISSUE THREAD

**Issue by Frisk9571** [MichaelEpicA/RBXTools#7]
Preferably to a 7z folder, but a regular folder will also do.

**Comment by MichaelEpicA** [comment]
Can this be a choice in like the typical 1 2 3 4 5 those options?

**Comment by Frisk9571** [comment]
Yes

**Comment by MichaelEpicA** [comment]
Should you be able to choose what path to save it to?

**Comment by MichaelEpicA** [comment]
Added in commit: https://github.com/MichaelEpicA/RBXTools/commit/4fbda86c29e80e90a4d6e7c7fac0f16f304c3122
